version: '3'
services:
  jenkins_master:
    build:
      context: ./master
      dockerfile: master.Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    links:
      - jenkins_agent
  jenkins_agent:
    build:
      context: ./slave
      dockerfile: slave.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    
